using System.Text;
using ScottPlotCookbook.Info;

namespace ScottPlotCookbook.Pages;

/// <summary>
/// The front page is /index.html and it lists all recipes.
/// Recipes are grouped by page, and pages are grouped by category.
/// </summary>
internal class FrontPage
{
    StringBuilder SB = new();

    private static string WrapPage(string content, string title) => @"<!doctype html>
        <html lang=""en"">
          <head>
            <meta charset=""utf-8"">
            <meta name=""viewport"" content=""width=device-width, initial-scale=1"">
            <title>{{TITLE}}</title>
            <link href=""https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"" rel=""stylesheet"" >
            <style>
            a {text-decoration: none;}
            a:hover {text-decoration: underline;}
            </style>
          </head>
          <body>
            <div class=""container"">
                <main>{{CONTENT}}</main>
            </div>
          </body>
        </html>"
        .Replace("{{TITLE}}", title)
        .Replace("{{CONTENT}}", content)
        .Replace("    ", "");

    public void Generate()
    {
        SB.AppendLine("<header class='text-center my-5'>");
        SB.AppendLine($"<h1>ScottPlot 5.0 Cookbook</h1>");
        SB.AppendLine($"Generated by <code>{ScottPlot.Version.InformalVersion}</code>");
        SB.AppendLine($"on {DateTime.Now.ToShortDateString()}");
        SB.AppendLine($"at {DateTime.Now.ToShortTimeString()}");
        SB.AppendLine("</header>");
        SB.AppendLine("<hr />");

        foreach (ChapterInfo chapter in Query.GetChapters())
        {
            if (!chapter.Pages.Any())
                continue;
            SB.AppendLine($"<h2 class='mt-5'>{chapter.ToString()}</h2>");
            chapter.Pages.ForEach(x => AddPage(x));
        }

        Export();
    }

    public void Export()
    {
        string partial = Path.Combine(CookbookGenerator.OutputFolder, "index.html");
        File.WriteAllText(partial, SB.ToString());
        TestContext.WriteLine($"SAVING: {partial}");

        string full = Path.Combine(CookbookGenerator.OutputFolder, "index.local.html");
        File.WriteAllText(full, WrapPage(SB.ToString(), "ScottPlot 5 Cookbook"));
        TestContext.WriteLine($"SAVING: {full}");
    }

    private void AddPage(PageInfo page)
    {
        SB.AppendLine($"<div class='fs-4 mt-4'>{page.Name}</div>");
        SB.AppendLine($"<div>{page.Description}</div>");
        page.Recipes.ForEach(x => AddRecipeImage(x));
    }

    private void AddRecipeImage(RecipeInfo recipe)
    {
        SB.AppendLine("<div class='d-flex'>");

        SB.AppendLine($"<a href='{recipe.ImageUrl}'><img src='{recipe.ImageUrl}' /></a>");

        SB.AppendLine("<div class='p-3'>");
        SB.AppendLine($"<div><a href='{recipe.ImageUrl}'><b>{recipe.Name}</b></a></div>");
        SB.AppendLine($"<div>{recipe.Description}</div>");
        SB.AppendLine("</div>");

        SB.AppendLine("</div>");
    }
}
