namespace ScottPlotCookbook.Generation;

internal class FrontPage : PageBase
{
    public override void Generate()
    {
        MD.AppendLine($"# ScottPlot Cookbook");
        MD.AppendLine($"");
        MD.AppendLine($"Generated by {ScottPlot.Version.InformalVersion} " +
            $"on {DateTime.Now.ToShortDateString()} " +
            $"at {DateTime.Now.ToShortTimeString()}");

        foreach (Chapter chapter in Cookbook.GetChapters())
        {
            MD.AppendLine($"\n### {chapter}");

            foreach (RecipePage page in Cookbook.GetPages(chapter))
            {
                MD.AppendLine($"* {page.PageName} - {page.PageDescription}");
                foreach (IRecipe recipe in Cookbook.GetRecipes(page))
                {
                    MD.AppendLine($"  * {recipe.Name}");
                }
            }
        }
    }
}
