using ScottPlotCookbook.Info;

namespace ScottPlotCookbook.HtmlPages;

internal class HtmlRecipePage : HtmlPageBase
{
    private readonly PageInfo Page;

    public HtmlRecipePage(PageInfo page, List<RecipeSource> sources)
    {
        Page = page;

        foreach (RecipeInfo recipe in Page.Recipes)
            recipe.AddSource(sources);
    }

    public void Generate()
    {
        SB.AppendLine("<header class='text-center my-5'>");
        SB.AppendLine($"<h1>ScottPlot 5.0 Cookbook</h1>");
        SB.AppendLine($"Generated by <code>{ScottPlot.Version.InformalVersion}</code>");
        SB.AppendLine($"on {DateTime.Now.ToShortDateString()}");
        SB.AppendLine($"at {DateTime.Now.ToShortTimeString()}");
        SB.AppendLine("</header>");

        SB.AppendLine("<hr />");

        SB.AppendLine($"<h1>{Page.Name}</h1>");

        SB.AppendLine("<hr />");

        foreach (RecipeInfo recipe in Page.Recipes)
        {
            SB.AppendLine($"<h3>{recipe.Name}</h3>");
            SB.AppendLine($"<p>{recipe.Description}</p>");
            SB.AppendLine($"<pre>{recipe.SourceCode}</pre>");

            SB.AppendLine($"<a href='{recipe.ImageFilename}'><img src='{recipe.ImageFilename}' /></a>");
        }

        string outputFolder = Path.Combine(Cookbook.OutputFolder, Page.FolderUrl);
        Save(outputFolder, $"{Page.Name} - ScottPlot 5.0 Cookbook");
    }
}
