using ScottPlotCookbook.MarkdownPages;

namespace ScottPlotCookbook.HtmlPages;

internal class HtmlPageGenerator
{
    [Test]
    public void Generate_Cookbook_Pages()
    {
        // this test assumes jpegs are generated by other tests
        List<RecipeSource> sources = SourceReading.GetRecipeSources();
        MakeHtmlPages(sources);
        MakeMarkdownPages(sources);
    }

    private void MakeHtmlPages(List<RecipeSource> sources)
    {
        HtmlFrontPage frontPage = new();
        frontPage.Generate();

        foreach (Info.PageInfo page in Query.GetPages())
        {
            HtmlRecipePage recipePage = new(page, sources);
            recipePage.Generate();
        }
    }

    private void MakeMarkdownPages(List<RecipeSource> sources)
    {
        MarkdownFrontPage frontPage = new();
        frontPage.Generate();

        foreach (Info.PageInfo page in Query.GetPages())
        {
            MarkdownRecipePage recipePage = new(page, sources);
            recipePage.Generate();
        }
    }
}
