namespace ScottPlotCookbook.HtmlPages;

internal class HtmlPageGenerator
{
    public static readonly string OutputFolder =
        Path.GetFullPath(Path.Combine(TestContext.CurrentContext.TestDirectory, "cookbook-output"));

    [Test]
    public void Generate_Cookbook_Pages()
    {
        // this test assumes jpegs are generated by other tests
        // TODO: assert output folder exists once and never again

        HtmlFrontPage frontPage = new();
        frontPage.Generate();

        foreach (Info.PageInfo page in Query.GetPages())
        {
            HtmlRecipePage recipePage = new(page);
            recipePage.Generate();
        }
    }
}
