namespace ScottPlotCookbook.HtmlPages;

internal class HtmlPageGenerator
{
    [Test]
    public void Generate_Cookbook_Pages()
    {
        // this test assumes jpegs are generated by other tests
        // TODO: assert output folder exists once and never again

        HtmlFrontPage frontPage = new();
        frontPage.Generate();

        List<RecipeSource> sources = SourceReading.GetRecipeSources();

        foreach (Info.PageInfo page in Query.GetPages())
        {
            HtmlRecipePage recipePage = new(page, sources);
            recipePage.Generate();
        }
    }
}
