global using System;
global using System.IO;
global using System.Linq;
global using System.Collections;
global using System.Collections.Generic;
global using System.Text;
global using ScottPlot.Extensions;
global using System.Diagnostics;
global using SkiaSharp;
