namespace ScottPlotCookbook;

internal class CookbookGenerator
{
    public static readonly string OutputFolder =
        Path.GetFullPath(Path.Combine(TestContext.CurrentContext.TestDirectory, "cookbook-output"));

    [Test]
    public void Generate_Cookbook_Pages()
    {
        // this test assumes jpegs are generated by other tests
        // TODO: assert output folder exists once and never again
        Pages.FrontPage page = new();
        page.Generate();
    }
}
