using NUnit.Framework;

namespace ScottPlotCookbook;

internal class CookbookGenerator
{
    public static string OutputFolder =>
        Path.GetFullPath(Path.Combine(TestContext.CurrentContext.TestDirectory, "cookbook-output"));

    public static string GetPagePath(RecipePageDetails pageDetails) =>
        Path.Combine(OutputFolder, Html.UrlSafe(pageDetails.PageName));

    public static string GetBaseImagePath(RecipePageDetails pageDetails, IRecipe recipe) =>
         Path.Combine(GetPagePath(pageDetails), Html.UrlSafe(recipe.Name));

    public static string GetBaseImageUrl(RecipePageDetails pageDetails, IRecipe recipe) =>
         GetBaseImagePath(pageDetails, recipe).Replace(OutputFolder, "").Replace("\\", "/").TrimStart('/');

    [Test]
    public void Generate_Cookbook_Pages()
    {
        // this test assumes jpegs are generated by other tests
        // TODO: assert output folder exists once and never again

        foreach (string oldHtmlFile in Directory.GetFiles(OutputFolder, "*.html"))
        {
            Console.WriteLine($"Deleting: {oldHtmlFile}");
            File.Delete(oldHtmlFile);
        }

        Pages.FrontPage page = new();
        page.Generate();
    }
}
