namespace ScottPlotTests.UnitTests;

public class ReportTests
{
    [Test]
    public void Test_HtmlReport_SaveToDisk()
    {
        // create some plots
        Plot plot1 = new();
        plot1.Add.Signal(Generate.Sin());

        Plot plot2 = new();
        plot2.Add.Signal(Generate.Cos());

        // create a platform-agnostic report
        ScottPlot.Reporting.Report report = new();
        report.AddHeading("Sine");
        report.AddText("A sine wave starts at zero");
        report.AddPlot(plot1);
        report.AddPageBreak();
        report.AddHeading("Cosine");
        report.AddText("A cosine wave starts at 1");
        report.AddPlot(plot2);

        // generate the report using a platform-specific exporter
        ScottPlot.Reporting.Export.HtmlReportExporter htmlReport = new(report)
        {
            Title = "Test Report",
            Description = "This report was generated by ScottPlot.UnitTests",
        };

        string saveAs = Path.GetFullPath("report.html");
        htmlReport.SaveAs(saveAs);
        System.Console.WriteLine(saveAs);
    }
}
