namespace ScottPlotCookbook.MarkdownPages;

internal class Generate
{
    [Test]
    public void Generate_Markdown_Pages()
    {
        // this test assumes jpegs have already been generated by other tests
        // TODO: make this test run last as part of the breakdown
        List<RecipeSource> sources = SourceReading.GetRecipeSources();
        GenerateHomePage(sources);
        GenerateCategoryPages(sources);
        GenerateRecipePages(sources);
        Console.WriteLine(Cookbook.OutputFolder);
    }

    private void GenerateHomePage(IEnumerable<RecipeSource> sources)
    {
        TestContext.WriteLine("Generating cookbook home page");
        FrontPage frontPage = new();
        frontPage.Generate();
    }

    private void GenerateCategoryPages(IEnumerable<RecipeSource> sources)
    {
        TestContext.WriteLine("Generating cookbook category pages");
        foreach (PageInfo page in Query.GetCategoryPages())
        {
            CategoryPage categoryPage = new(page, sources);
            categoryPage.Generate();
        }
    }

    private void GenerateRecipePages(IEnumerable<RecipeSource> sources)
    {
        TestContext.WriteLine("Generating cookbook recipe pages");
        foreach (RecipeInfo recipe in Query.GetRecipes())
        {
            RecipePage recipePage = new(recipe, sources);
            recipePage.Generate();
        }
    }
}
