namespace ScottPlotCookbook.MarkdownPages;

internal class Generate
{
    [Test]
    public void Generate_Markdown_Pages()
    {
        // this test assumes jpegs have already been generated by other tests
        // TODO: make this test run last as part of the breakdown
        List<RecipeInfo> sources = SourceReading.GetRecipeSources();

        foreach (RecipeInfo recipe in sources)
        {
            if (recipe.Category is null)
                throw new InvalidOperationException($"unpopulated cateogry {recipe}");

            if (recipe.SourceCode is null)
                throw new InvalidOperationException($"unpopulated source {recipe}");
        }

        GenerateHomePage(sources);
        GenerateCategoryPages(sources);
        GenerateRecipePages(sources);
        Console.WriteLine(Cookbook.OutputFolder);
    }

    private void GenerateHomePage(List<RecipeInfo> sources)
    {
        TestContext.WriteLine("Generating cookbook home page");
        FrontPage frontPage = new(sources);
        frontPage.Generate();
    }

    private void GenerateCategoryPages(List<RecipeInfo> sources)
    {
        List<CategoryInfo> knownPages = Query.GetCategories();

        TestContext.WriteLine("Generating cookbook category pages");
        foreach (string category in sources.Select(x => x.Category).Distinct())
        {
            CategoryInfo info = knownPages.Where(x => x.Name == category).Single();

            foreach (RecipeInfo source in sources.Where(x => x.Category == category))
            {
                CategoryPage cp = new(sources, info);
                cp.Generate();
            }
        }
    }

    private void GenerateRecipePages(List<RecipeInfo> sources)
    {
        TestContext.WriteLine("Generating cookbook recipe pages");
        foreach (RecipeInfo recipe in Query.GetRecipes())
        {
            RecipePage recipePage = new(recipe);
            recipePage.Generate();
        }
    }
}
