$paths = @(
    (Resolve-Path "../../src"),
    (Resolve-Path "../../dev")
)
$csFiles = Get-ChildItem -Path $paths -Recurse -Filter *.cs -File

$folderNames = @(
    "ScottPlot5", 
    "ScottPlot5 Tests", 
    "ScottPlot5 Controls", 
    "ScottPlot5 Cookbook"
)

$folderMatchOrder = @(
    "ScottPlot5 Tests", 
    "ScottPlot5 Controls", 
    "ScottPlot5 Cookbook",
    "ScottPlot5" # must be last
)

$results = $csFiles | ForEach-Object {
    $content = Get-Content $_.FullName
    $lines = $content.Length
    $isGenerated =
        $_.Name -like "*.g.cs" -or
        $_.Name -like "*.designer.cs" -or
        $_.FullName -match "\\(bin|obj)\\" -or
        ($content[0..([Math]::Min(19, $content.Length-1))] -join "`n") -match "<auto-generated>"

    # Match the first (most specific) folder name found in the path
    $matchedFolder = $null
    foreach ($folder in $folderMatchOrder) {
        if ($_.FullName -match [regex]::Escape("\$folder\")) {
            $matchedFolder = $folder
            break
        }
    }

    [PSCustomObject]@{
        Lines         = $lines
        Generated     = $isGenerated
        MatchedFolder = $matchedFolder
    }
}

$totalLines     = ($results | Measure-Object -Property Lines -Sum).Sum
$generatedLines = ($results | Where-Object Generated | Measure-Object -Property Lines -Sum).Sum
$humanLines     = $totalLines - $generatedLines
$totalFiles = $csFiles.Count

Write-Host ("Total: {0:N0} Total LOC across {1:N0} files" -f $totalLines, $totalFiles)

foreach ($folder in $folderNames) {
    $folderResults = $results | Where-Object { $_.MatchedFolder -eq $folder }
    $folderFiles   = $folderResults.Count
    $folderTotal   = ($folderResults | Measure-Object -Property Lines -Sum).Sum
    $folderGen     = ($folderResults | Where-Object Generated | Measure-Object -Property Lines -Sum).Sum
    $folderHuman   = $folderTotal - $folderGen
    Write-Host ("{0}: {1:N0} LOC across {2:N0} files" -f $folder, $folderTotal, $folderFiles)
}