name: PR

on:
  workflow_dispatch:
  pull_request:

jobs:
  evaluate:
    name: Evaluate Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # all branches
      - name: Evaluate git history
        run: |
          echo "MOD_SP4=$(git diff main ${{ github.event.pull_request.head.sha }} --name-only | grep src/ScottPlot4/)" >> $GITHUB_ENV
          echo "MOD_SP5=$(git diff main ${{ github.event.pull_request.head.sha }} --name-only | grep src/ScottPlot5/)" >> $GITHUB_ENV
          echo $MOD_SP4
          echo $MOD_SP5
      - name: ScottPlot4 Changed
        if: ${{ env.MOD_SP4 != '' }}
        run: echo sp4 changed
      - name: ScottPlot5 Changed
        if: ${{ env.MOD_SP5 != '' }}
        run: echo sp5 changed
    outputs:
      MOD_SP4: ${{ steps.evaluate.outputs.MOD_SP4 != '' }}
      MOD_SP5: ${{ steps.evaluate.outputs.MOD_SP5 != '' }}

  sp4-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP4 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp4-check.yaml
    permissions:
      security-events: write

  sp5-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp5-check.yaml
    permissions:
      security-events: write

  sp4-full:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP4 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp4-full-build.yaml
    permissions:
      security-events: write

  sp5-full:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp5-full-build.yaml
    permissions:
      security-events: write

  autoformat-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-autoformat-check.yaml
    permissions:
      security-events: write
