name: PR

on:
  workflow_dispatch:
  pull_request:

jobs:
  evaluate:
    name: Evaluate Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # all branches
      - name: Evaluate git history
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-only > changed.txt
          grep src/ScottPlot4/ changed.txt > changed4.txt
          grep src/ScottPlot5/ changed.txt > changed5.txt
          echo "MOD_SP4=$(cat changed4.txt)" >> $GITHUB_ENV
          echo "MOD_SP5=$(cat changed5.txt)" >> $GITHUB_ENV
      - name: ScottPlot4 Changed ${{ env.MOD_SP4 }}
        if: ${{ env.MOD_SP4 != '' }}
        run: echo sp4 changed
      - name: ScottPlot5 Changed ${{ env.MOD_SP5 }}
        if: ${{ env.MOD_SP5 != '' }}
        run: echo sp5 changed
    outputs:
      MOD_SP4: ${{ steps.evaluate.outputs.MOD_SP4 != '' }}
      MOD_SP5: ${{ steps.evaluate.outputs.MOD_SP5 != '' }}

  sp4-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP4 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp4-check.yaml
    permissions:
      security-events: write

  sp5-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp5-check.yaml
    permissions:
      security-events: write

  sp4-full:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP4 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp4-full-build.yaml
    permissions:
      security-events: write

  sp5-full:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp5-full-build.yaml
    permissions:
      security-events: write

  autoformat-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-autoformat-check.yaml
    permissions:
      security-events: write
