# This workflow is used for quickly evaluating whether PRs are ready to merge.
# It checks for basic compile errors and ensures tests pass.

name: PR1

on:
  workflow_dispatch:
  pull_request:

jobs:
  quick:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"
      - name: Build ScottPlot
        run: dotnet build "src/ScottPlot5/ScottPlot5/ScottPlot.csproj"
      - name: Build Tests
        run: dotnet build "src/ScottPlot5/ScottPlot5 Tests/Unit Tests/ScottPlot Unit Tests.csproj"
      - name: Build Cookbook
        run: dotnet build "src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj"
      - name: Build WinForms Demo
        run: dotnet build "src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj"
      - name: Build WPF Demo
        run: dotnet build "src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WPF Demo/WPF Demo.csproj"
      - name: Run Unit Tests
        run: dotnet test "src/ScottPlot5/ScottPlot5 Tests/Unit Tests/ScottPlot Unit Tests.csproj" --configuration Release --verbosity minimal
      - name: Run Cookbook Tests
        run: dotnet test "src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj" --configuration Release --verbosity minimal
