# This workflow is used for quickly evaluating whether PRs are ready to merge.
# It checks for basic compile errors and ensures tests pass.

name: PR1

on:
  workflow_dispatch:
  pull_request:

jobs:
  quick:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: bash .github/workflows/scripts/check-build.sh
      - name: Test
        run: bash .github/workflows/scripts/check-test.sh
