# This workflow is used for quickly evaluating whether PRs are ready to merge.
# It checks for basic compile errors and ensures tests pass.

name: PR1

on:
  workflow_dispatch:
  pull_request:

jobs:
  evaluate:
    uses: ./.github/workflows/task-pr-changes.yaml

  sp4-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP4 == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp4-check.yaml
    permissions:
      security-events: write

  sp5-check:
    needs: evaluate
    if: needs.evaluate.outputs.MOD_SP5 == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/task-sp5-check.yaml
    permissions:
      security-events: write
