# This workflow tests all code after any change to the main branch

name: Update Changelog Webpage

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  publish-changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Trigger Remote Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/scottplot/scottplot.net/actions/workflows/changelog.yaml/dispatches \
            -d '{"ref":"main"}'
