name: Full Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SOLUTION_FILE: "./src/ScottPlot5/ScottPlot5.sln"

jobs:
  full:
    name: Full Build
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        #with:
          #dotnet-version: "9.0"
          #dotnet-quality: "preview"
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Restore Workloads
        run: dotnet workload restore ${{ env.SOLUTION_FILE }}
      - name: Restore Solution
        run: dotnet restore ${{ env.SOLUTION_FILE }}
      - name: Build Solution
        run: dotnet build  ${{ env.SOLUTION_FILE }} --configuration Release
      - name: Run Tests
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --verbosity minimal
      - name: Security Scan
        uses: github/codeql-action/analyze@v3
